"""Utility helpers for the FluidX_Blender addon.

Covers:
  - FluidX3D C++ setup-file generation (mesh-aware, with collision/inflow support)
  - defines.hpp patching to enable required FluidX3D features before compilation
  - Exporting Blender objects as binary STL files for voxelization
  - Loading OBJ / PLY surface meshes produced by FluidX3D
  - Loading legacy ASCII/binary VTK files (POLYDATA, UNSTRUCTURED_GRID,
    and STRUCTURED_POINTS) as Blender mesh or volume objects
  - Converting binary VTK STRUCTURED_POINTS density fields to OpenVDB (.vdb)
"""

import os
import struct
import logging
from typing import Optional

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# C++ setup-file generation  (object-aware, v2)
# ---------------------------------------------------------------------------

_SETUP_TEMPLATE = """\
// FluidX3D simulation setup – generated by FluidX_Blender {version}
// Domain object: {domain_name}
// WARNING: This file is overwritten every bake. Do not edit manually.

#include "setup.hpp"

void main_setup() {{
    // ---- Domain ----
    const uint Nx = {Nx}u, Ny = {Ny}u, Nz = {Nz}u;
    const float nu = {nu}f;

#ifdef VOLUME_FORCE
    LBM lbm(Nx, Ny, Nz, nu, {fx}f, {fy}f, {fz}f);
#else
    LBM lbm(Nx, Ny, Nz, nu);
#endif // VOLUME_FORCE

    // ---- Solid collision geometry (voxelized from exported STL meshes) ----
{collision_code}
    // ---- Initialize fluid fields ----
    const ulong n_total = lbm.get_N();
    for(ulong n=0ull; n<n_total; n++) {{
        if(lbm.flags[n] != TYPE_S) {{
            lbm.rho[n] = {rho}f;
            lbm.u.x[n] = 0.0f;
            lbm.u.y[n] = 0.0f;
            lbm.u.z[n] = 0.0f;
            lbm.flags[n] = TYPE_F;
        }}
    }}

#ifdef EQUILIBRIUM_BOUNDARIES
    // ---- Inflow / outflow equilibrium boundary regions ----
{inflow_outflow_code}
#endif // EQUILIBRIUM_BOUNDARIES

    // ---- Domain-face boundary conditions ----
{boundary_code}
    lbm.flags.write_to_device();
    lbm.rho.write_to_device();
    lbm.u.write_to_device();

    // ---- Run simulation and export VTK volume data ----
    mkdir_p("{out_dir}");
    while(lbm.get_t() <= {time_steps}ull) {{
        if(lbm.get_t() % {output_every}ull == 0ull) {{
            lbm.rho.write_device_to_vtk("{out_dir}/rho");
            lbm.u.write_device_to_vtk("{out_dir}/u");
        }}
        lbm.run(1u, {time_steps}ull);
    }}
}}
"""

# Map human-readable boundary names to FluidX3D flag types
_BC_FLAG = {
    "PERIODIC":    "TYPE_P",
    "WALL":        "TYPE_S",
    "FREE_SLIP":   "TYPE_S",  # treated as no-slip wall; free-slip needs custom kernel
    "EQUILIBRIUM": "TYPE_E",
}


def _bc(name: str) -> str:
    return _BC_FLAG.get(name, "TYPE_S")


def get_domain_object(scene):
    """Return the first object in *scene* tagged as DOMAIN, or None."""
    for obj in scene.objects:
        if hasattr(obj, "fluidx") and obj.fluidx.object_type == "DOMAIN":
            return obj
    return None


def get_objects_by_type(scene, type_name: str) -> list:
    """Return all objects in *scene* tagged with the given FluidX type."""
    return [
        obj for obj in scene.objects
        if hasattr(obj, "fluidx") and obj.fluidx.object_type == type_name
    ]


def get_domain_world_bounds(domain_obj):
    """Return (min_corner, max_corner) of the domain object in world space.

    Returns two mathutils.Vector instances (or plain tuples if mathutils is
    not available in the current context).
    """
    corners = [domain_obj.matrix_world @ domain_obj.data.vertices[vi].co
               for vi in range(len(domain_obj.data.vertices))]
    if not corners:
        # Fall back to bounding-box corners
        import mathutils
        corners = [domain_obj.matrix_world @ mathutils.Vector(c)
                   for c in domain_obj.bound_box]

    min_x = min(v[0] for v in corners)
    min_y = min(v[1] for v in corners)
    min_z = min(v[2] for v in corners)
    max_x = max(v[0] for v in corners)
    max_y = max(v[1] for v in corners)
    max_z = max(v[2] for v in corners)
    return (min_x, min_y, min_z), (max_x, max_y, max_z)


def world_to_lattice(world_pos, domain_bounds, domain_res):
    """Map a world-space position to FluidX3D lattice coordinates.

    FluidX3D lattice positions are centred at the box centre and span
    roughly [-N/2, N/2] in each axis.  voxelize_stl() expects positions in
    these lattice units.
    """
    (min_x, min_y, min_z), (max_x, max_y, max_z) = domain_bounds
    Nx, Ny, Nz = domain_res

    wx = max_x - min_x or 1.0
    wy = max_y - min_y or 1.0
    wz = max_z - min_z or 1.0

    lx = ((world_pos[0] - (min_x + max_x) * 0.5) / wx) * Nx
    ly = ((world_pos[1] - (min_y + max_y) * 0.5) / wy) * Ny
    lz = ((world_pos[2] - (min_z + max_z) * 0.5) / wz) * Nz
    return lx, ly, lz


def world_size_to_lattice(world_size, domain_bounds, domain_res):
    """Map a world-space extent to the corresponding lattice-unit size."""
    (min_x, min_y, min_z), (max_x, max_y, max_z) = domain_bounds
    Nx, Ny, Nz = domain_res
    sx = (max_x - min_x) or 1.0
    sy = (max_y - min_y) or 1.0
    sz = (max_z - min_z) or 1.0
    lx = (world_size[0] / sx) * Nx
    ly = (world_size[1] / sy) * Ny
    lz = (world_size[2] / sz) * Nz
    return lx, ly, lz


def export_object_as_stl(obj, filepath: str) -> bool:
    """Export *obj* as a binary STL file to *filepath*.

    Returns True on success, False if the operation fails.
    Requires a valid Blender context (call from an operator).
    """
    import bpy

    # Deselect all, then select only the target object
    prev_active = bpy.context.view_layer.objects.active
    prev_mode = bpy.context.object.mode if bpy.context.object else "OBJECT"

    if prev_mode != "OBJECT":
        bpy.ops.object.mode_set(mode="OBJECT")

    bpy.ops.object.select_all(action="DESELECT")
    obj.select_set(True)
    bpy.context.view_layer.objects.active = obj

    try:
        bpy.ops.wm.stl_export(
            filepath=filepath,
            export_selected_objects=True,
            apply_modifiers=True,
            ascii_format=False,  # binary STL (required by FluidX3D)
        )
        success = True
    except Exception as exc:
        log.error("STL export failed for %s: %s", obj.name, exc)
        success = False

    # Restore previous state
    bpy.ops.object.select_all(action="DESELECT")
    bpy.context.view_layer.objects.active = prev_active
    return success


def generate_bake_setup_code(props, scene, out_dir: str, stl_dir: str) -> str:
    """Generate a FluidX3D setup.cpp that embeds scene objects.

    *props*    – scene.fluidx (FluidXProperties)
    *scene*    – bpy.types.Scene
    *out_dir*  – absolute path where VTK output will be written (forward
                  slashes, embedded in the C++ string literal)
    *stl_dir*  – absolute path where exported STL files are stored
    """
    from . import bl_info  # noqa: F401 – for version string
    version = "0.2"

    Nx, Ny, Nz = props.domain_res_x, props.domain_res_y, props.domain_res_z
    domain_res = (Nx, Ny, Nz)
    domain_name = "N/A"

    # --- Domain bounds ---
    domain_obj = get_domain_object(scene)
    if domain_obj:
        domain_name = domain_obj.name
        try:
            domain_bounds = get_domain_world_bounds(domain_obj)
        except Exception:
            domain_bounds = ((-Nx / 2, -Ny / 2, -Nz / 2), (Nx / 2, Ny / 2, Nz / 2))
    else:
        domain_bounds = ((-Nx / 2, -Ny / 2, -Nz / 2), (Nx / 2, Ny / 2, Nz / 2))

    # --- Collision geometry ---
    collision_lines = []
    for obj in get_objects_by_type(scene, "COLLISION"):
        stl_path = os.path.join(stl_dir, f"collision_{_safe_name(obj.name)}.stl")
        # Compute world bounding box for this object
        try:
            import mathutils
            bb_world = [obj.matrix_world @ mathutils.Vector(c) for c in obj.bound_box]
        except Exception:
            bb_world = []

        if bb_world:
            obj_min = tuple(min(v[i] for v in bb_world) for i in range(3))
            obj_max = tuple(max(v[i] for v in bb_world) for i in range(3))
            obj_center_w = tuple((obj_min[i] + obj_max[i]) * 0.5 for i in range(3))
            obj_size_w = tuple(obj_max[i] - obj_min[i] for i in range(3))

            lc = world_to_lattice(obj_center_w, domain_bounds, domain_res)
            ls = world_size_to_lattice(obj_size_w, domain_bounds, domain_res)
            lsize = max(ls)  # voxelize_stl uses a single float for size
            stl_fwd = stl_path.replace("\\", "/")
            collision_lines.append(
                f'    lbm.voxelize_stl("{stl_fwd}", '
                f'float3({lc[0]:.4f}f, {lc[1]:.4f}f, {lc[2]:.4f}f), '
                f'{lsize:.4f}f, TYPE_S);  // {obj.name}'
            )
        else:
            stl_fwd = stl_path.replace("\\", "/")
            collision_lines.append(
                f'    lbm.voxelize_stl("{stl_fwd}", TYPE_S);  // {obj.name} (auto-center)'
            )

    collision_code = "\n".join(collision_lines) if collision_lines else \
        "    // (no collision objects)"

    # --- Inflow / outflow ---
    inflow_outflow_lines = []
    for obj in get_objects_by_type(scene, "INFLOW"):
        try:
            import mathutils
            bb_world = [obj.matrix_world @ mathutils.Vector(c) for c in obj.bound_box]
        except Exception:
            bb_world = []
        if not bb_world:
            continue
        obj_min = tuple(min(v[i] for v in bb_world) for i in range(3))
        obj_max = tuple(max(v[i] for v in bb_world) for i in range(3))
        # Lattice index range (clamp to [0, N-1])
        lmin = [max(0, int(world_to_lattice(obj_min, domain_bounds, domain_res)[i] + Nk / 2))
                for i, Nk in enumerate([Nx, Ny, Nz])]
        lmax = [min(Nk - 1, int(world_to_lattice(obj_max, domain_bounds, domain_res)[i] + Nk / 2))
                for i, Nk in enumerate([Nx, Ny, Nz])]
        vx, vy, vz = obj.fluidx.inflow_velocity
        rho_in = obj.fluidx.inflow_density
        inflow_outflow_lines.append(
            f"    // Inflow: {obj.name}"
            f"\n    for(uint z={lmin[2]}u; z<={lmax[2]}u; z++) {{"
            f"\n        for(uint y={lmin[1]}u; y<={lmax[1]}u; y++) {{"
            f"\n            for(uint x={lmin[0]}u; x<={lmax[0]}u; x++) {{"
            f"\n                const ulong n = lbm.index(x, y, z);"
            f"\n                lbm.flags[n] = TYPE_E;"
            f"\n                lbm.rho[n] = {rho_in:.4f}f;"
            f"\n                lbm.u.x[n] = {vx:.6f}f;"
            f"\n                lbm.u.y[n] = {vy:.6f}f;"
            f"\n                lbm.u.z[n] = {vz:.6f}f;"
            f"\n            }}"
            f"\n        }}"
            f"\n    }}"
        )

    for obj in get_objects_by_type(scene, "OUTFLOW"):
        try:
            import mathutils
            bb_world = [obj.matrix_world @ mathutils.Vector(c) for c in obj.bound_box]
        except Exception:
            bb_world = []
        if not bb_world:
            continue
        obj_min = tuple(min(v[i] for v in bb_world) for i in range(3))
        obj_max = tuple(max(v[i] for v in bb_world) for i in range(3))
        lmin = [max(0, int(world_to_lattice(obj_min, domain_bounds, domain_res)[i] + Nk / 2))
                for i, Nk in enumerate([Nx, Ny, Nz])]
        lmax = [min(Nk - 1, int(world_to_lattice(obj_max, domain_bounds, domain_res)[i] + Nk / 2))
                for i, Nk in enumerate([Nx, Ny, Nz])]
        inflow_outflow_lines.append(
            f"    // Outflow: {obj.name}"
            f"\n    for(uint z={lmin[2]}u; z<={lmax[2]}u; z++) {{"
            f"\n        for(uint y={lmin[1]}u; y<={lmax[1]}u; y++) {{"
            f"\n            for(uint x={lmin[0]}u; x<={lmax[0]}u; x++) {{"
            f"\n                lbm.flags[lbm.index(x, y, z)] = TYPE_E;"
            f"\n            }}"
            f"\n        }}"
            f"\n    }}"
        )

    inflow_outflow_code = "\n".join(inflow_outflow_lines) if inflow_outflow_lines else \
        "    // (no inflow/outflow objects)"

    # --- Domain-face boundary conditions ---
    bc_lines = []
    face_cfg = [
        ("X-", "x==0u",        props.bc_x_neg),
        ("X+", "x==Nx-1u",     props.bc_x_pos),
        ("Y-", "y==0u",        props.bc_y_neg),
        ("Y+", "y==Ny-1u",     props.bc_y_pos),
        ("Z-", "z==0u",        props.bc_z_neg),
        ("Z+", "z==Nz-1u",     props.bc_z_pos),
    ]
    non_wall = [(label, cond, bc) for label, cond, bc in face_cfg if bc != "WALL"]
    if non_wall:
        bc_lines.append("    const uint Nx=lbm.get_Nx(), Ny=lbm.get_Ny(), Nz=lbm.get_Nz();")
        bc_lines.append(
            "    for(ulong n=0ull; n<lbm.get_N(); n++) {"
            " uint x=0u, y=0u, z=0u; lbm.coordinates(n, x, y, z);"
        )
        for label, cond, bc in non_wall:
            bc_lines.append(f"        if({cond}) lbm.flags[n] = {_bc(bc)};  // {label}")
        bc_lines.append("    }")
    boundary_code = "\n".join(bc_lines) if bc_lines else "    // (all faces are solid walls by default)"

    out_fwd = out_dir.replace("\\", "/")
    fx, fy, fz = props.gravity

    return _SETUP_TEMPLATE.format(
        version=version,
        domain_name=domain_name,
        Nx=Nx, Ny=Ny, Nz=Nz,
        nu=props.viscosity,
        fx=fx, fy=fy, fz=fz,
        rho=props.density,
        collision_code=collision_code,
        inflow_outflow_code=inflow_outflow_code,
        boundary_code=boundary_code,
        out_dir=out_fwd,
        time_steps=props.time_steps,
        output_every=props.output_every,
    )


def _safe_name(name: str) -> str:
    """Convert a Blender object name to a filesystem-safe string."""
    return "".join(c if c.isalnum() or c in "-_." else "_" for c in name)


def write_bake_setup_file(props, scene, fluidx_src_dir: str, out_dir: str, stl_dir: str) -> str:
    """Write the generated setup.cpp into *fluidx_src_dir*/setup.cpp."""
    os.makedirs(fluidx_src_dir, exist_ok=True)
    code = generate_bake_setup_code(props, scene, out_dir, stl_dir)
    path = os.path.join(fluidx_src_dir, "setup.cpp")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(code)
    return path


# ---------------------------------------------------------------------------
# defines.hpp patching
# ---------------------------------------------------------------------------

def patch_defines_hpp(fluidx_src_dir: str, gravity_enabled: bool = False) -> None:
    """Patch FluidX3D's defines.hpp to enable the features required by a bake.

    Changes made:
    * ``#define BENCHMARK``         → commented out  (benchmark disables everything)
    * ``EQUILIBRIUM_BOUNDARIES``    → uncommented    (for inflow/outflow TYPE_E cells)
    * ``VOLUME_FORCE``              → uncommented if *gravity_enabled* is True

    All other settings are left unchanged.
    """
    path = os.path.join(fluidx_src_dir, "defines.hpp")
    if not os.path.isfile(path):
        raise FileNotFoundError(f"defines.hpp not found at {path}")

    with open(path, "r", encoding="utf-8") as fh:
        content = fh.read()

    # Disable BENCHMARK (it undef's everything and runs a benchmark setup)
    content = _set_define(content, "BENCHMARK", enable=False)

    # Enable EQUILIBRIUM_BOUNDARIES (needed for TYPE_E inflow/outflow)
    content = _set_define(content, "EQUILIBRIUM_BOUNDARIES", enable=True)

    # Enable VOLUME_FORCE only when gravity is non-zero
    content = _set_define(content, "VOLUME_FORCE", enable=gravity_enabled)

    with open(path, "w", encoding="utf-8") as fh:
        fh.write(content)


def _set_define(content: str, name: str, enable: bool) -> str:
    """Enable or disable a ``#define NAME`` line in *content*."""
    import re
    # Match both "#define NAME" and "//#define NAME" variants
    pattern = re.compile(r"^(//\s*)?#define\s+" + re.escape(name) + r"(\s.*)?$", re.MULTILINE)
    if enable:
        replacement = f"#define {name}"
    else:
        replacement = f"//#define {name}"

    if pattern.search(content):
        content = pattern.sub(replacement, content)
    else:
        # Append if not found
        content += f"\n{replacement}\n"
    return content


# ---------------------------------------------------------------------------
# Legacy setup.cpp generation (kept for backward compatibility)
# ---------------------------------------------------------------------------

_SETUP_TEMPLATE_LEGACY = """\
// FluidX3D simulation setup – generated by FluidX_Blender
// Place this file as  <FluidX3D>/src/setup.cpp  and recompile.

#include "src/lbm.hpp"
#include "src/units.hpp"

void main_setup() {{
    // ---- Domain ----
    const uint Nx = {Nx}u;
    const uint Ny = {Ny}u;
    const uint Nz = {Nz}u;

    // ---- Physics ----
    // kinematic viscosity (lattice units); Re = u_max * L / nu
    const float nu = {nu}f;
    // fluid density (lattice units)
    const float rho = {rho}f;

    // ---- Boundary conditions ----
    // Each face: P=periodic  W=no-slip wall  F=free-slip  V=velocity
    const uchar  boundary_x_neg = {bc_x_neg};
    const uchar  boundary_x_pos = {bc_x_pos};
    const uchar  boundary_y_neg = {bc_y_neg};
    const uchar  boundary_y_pos = {bc_y_pos};
    const uchar  boundary_z_neg = {bc_z_neg};
    const uchar  boundary_z_pos = {bc_z_pos};

    LBM lbm(Nx, Ny, Nz, nu);

    // ---- Initial conditions ----
    // Set the initial density and velocity fields here.
    const uint n = lbm.get_N();
    for (uint i = 0u; i < n; i++) {{
        lbm.rho[i] = rho;
        lbm.u.x[i] = 0.0f;
        lbm.u.y[i] = 0.0f;
        lbm.u.z[i] = 0.0f;
        lbm.flags[i] = TYPE_F;  // fluid
    }}

    // ---- Boundary flags ----
    lbm.flags.write_to_device();
    lbm.rho.write_to_device();
    lbm.u.write_to_device();

    // ---- Output settings ----
    lbm.graphics.set_camera_free(
        float3(0.5f * Nx, -2.0f * Ny, 0.5f * Nz),
        float3(0.5f * Nx, 0.5f * Ny, 0.5f * Nz)
    );

    // ---- Run ----
    while (lbm.get_t() <= {time_steps}u) {{
        if (lbm.get_t() % {output_every}u == 0u) {{
#ifdef EXPORT_VTK
            lbm.vtk_export_lbm(lbm.get_t());
#endif
#ifdef EXPORT_MESH
            lbm.vtk_export_surface(lbm.get_t());
#endif
        }}
        lbm.run(1u, {time_steps}u);
    }}
}}
"""

_BC_FLAG_LEGACY = {
    "PERIODIC": "TYPE_P",
    "WALL": "TYPE_W",
    "FREE_SLIP": "TYPE_S",
    "VELOCITY": "TYPE_V",
}


def generate_setup_code(props) -> str:
    """(Legacy) Return a FluidX3D setup.cpp string built from *props*."""
    def bc(name: str) -> str:
        return _BC_FLAG_LEGACY.get(name, "TYPE_W")

    return _SETUP_TEMPLATE_LEGACY.format(
        Nx=props.domain_res_x,
        Ny=props.domain_res_y,
        Nz=props.domain_res_z,
        nu=props.viscosity,
        rho=props.density,
        bc_x_neg=bc(props.bc_x_neg),
        bc_x_pos=bc(props.bc_x_pos),
        bc_y_neg=bc(props.bc_y_neg),
        bc_y_pos=bc(props.bc_y_pos),
        bc_z_neg=bc(props.bc_z_neg),
        bc_z_pos=bc(props.bc_z_pos),
        time_steps=props.time_steps,
        output_every=props.output_every,
    )


def write_setup_file(props, output_dir: str) -> str:
    """(Legacy) Write the generated setup.cpp to *output_dir* and return its path."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "setup.cpp")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(generate_setup_code(props))
    return path


# ---------------------------------------------------------------------------
# VTK → OpenVDB conversion
# ---------------------------------------------------------------------------

def _read_vtk_binary_structured_points(filepath: str):
    """Parse a binary VTK STRUCTURED_POINTS file.

    Returns ``(data_array, (Nx, Ny, Nz))`` where *data_array* is a numpy
    array shaped ``(Nz, Ny, Nx)`` (z-major, matching VTK storage order).

    Only the first scalar field is read (SCALARS keyword).  The caller is
    responsible for selecting the correct file (e.g. ``rho_*.vtk``).
    """
    import numpy as np

    dims = (1, 1, 1)
    data_type_str = "float"
    n_components = 1
    in_point_data = False

    with open(filepath, "rb") as f:
        # --- ASCII header ---
        header_bytes = []
        while True:
            line_bytes = f.readline()
            if not line_bytes:
                break
            header_bytes.append(line_bytes)
            line = line_bytes.decode("ascii", errors="replace").strip()
            parts = line.split()
            if not parts:
                continue
            kw = parts[0].upper()
            if kw == "DIMENSIONS" and len(parts) >= 4:
                dims = (int(parts[1]), int(parts[2]), int(parts[3]))
            elif kw == "POINT_DATA":
                in_point_data = True
            elif in_point_data and kw == "SCALARS" and len(parts) >= 3:
                data_type_str = parts[2].lower()
                n_components = int(parts[3]) if len(parts) > 3 else 1
            elif kw == "LOOKUP_TABLE":
                # Binary data starts immediately after this line
                break

        # --- Binary payload ---
        dtype_map = {
            "float":         ">f4",
            "double":        ">f8",
            "int":           ">i4",
            "unsigned_int":  ">u4",
            "short":         ">i2",
            "unsigned_short": ">u2",
            "char":          ">i1",
            "unsigned_char": ">u1",
        }
        np_dtype = dtype_map.get(data_type_str, ">f4")
        raw = f.read()

    Nx, Ny, Nz = dims
    arr = np.frombuffer(raw, dtype=np_dtype)

    if n_components > 1:
        arr = arr.reshape(Nz, Ny, Nx, n_components)
    else:
        arr = arr.reshape(Nz, Ny, Nx)

    return arr, dims


def vtk_binary_to_vdb(vtk_path: str, vdb_path: str, threshold: float = 0.005) -> str:
    """Convert a binary VTK STRUCTURED_POINTS density field to OpenVDB.

    *vtk_path*  – path to the ``rho_*.vtk`` file written by FluidX3D
    *vdb_path*  – output ``.vdb`` file path
    *threshold* – density values below this are treated as empty (gas/solid)

    Requires ``pyopenvdb`` (bundled with Blender 3.0+ OpenVDB builds) and
    ``numpy``.  Raises RuntimeError if either dependency is unavailable.
    """
    try:
        import pyopenvdb as vdb  # type: ignore
    except ImportError as exc:
        raise RuntimeError(
            "pyopenvdb is not available in this Blender build.  "
            "Install Blender with OpenVDB support or convert VTK files manually."
        ) from exc

    import numpy as np

    arr, dims = _read_vtk_binary_structured_points(vtk_path)
    Nx, Ny, Nz = dims

    # arr is (Nz, Ny, Nx) float32 – convert to float32 and clamp
    density = arr.astype(np.float32)
    density = np.clip(density, 0.0, None)

    # Create an OpenVDB fog volume grid
    grid = vdb.FloatGrid()
    grid.name = "density"
    grid.gridClass = vdb.GridClass.FOG_VOLUME
    grid.background = 0.0

    # pyopenvdb.copyFromArray expects the array indexed as arr[x, y, z].
    # Our VTK data is (Nz, Ny, Nx) in memory (z outer, x inner), which is
    # equivalent to arr[z, y, x].  Transposing gives arr[x, y, z].
    grid.copyFromArray(density.T, ijk_min=(0, 0, 0), tolerance=threshold)

    os.makedirs(os.path.dirname(vdb_path) or ".", exist_ok=True)
    vdb.write(vdb_path, grids=[grid])
    return vdb_path


def convert_vtk_cache_to_vdb(vtk_dir: str, vdb_dir: str) -> list:
    """Convert all ``rho_*.vtk`` files in *vtk_dir* to ``.vdb`` files in *vdb_dir*.

    Files are sorted by name so that frame order is preserved.
    Returns the list of generated ``.vdb`` file paths.
    """
    import glob as _glob

    vtk_files = sorted(_glob.glob(os.path.join(vtk_dir, "rho*.vtk")))
    if not vtk_files:
        log.warning("No rho*.vtk files found in %s", vtk_dir)
        return []

    os.makedirs(vdb_dir, exist_ok=True)
    vdb_paths = []
    for vtk_path in vtk_files:
        base = os.path.splitext(os.path.basename(vtk_path))[0]
        vdb_path = os.path.join(vdb_dir, base + ".vdb")
        try:
            vtk_binary_to_vdb(vtk_path, vdb_path)
            vdb_paths.append(vdb_path)
            log.info("Converted %s → %s", vtk_path, vdb_path)
        except Exception as exc:
            log.error("Failed to convert %s: %s", vtk_path, exc)

    return vdb_paths


# ---------------------------------------------------------------------------
# OBJ / PLY surface-mesh loader
# ---------------------------------------------------------------------------


def load_obj_as_mesh(context, filepath: str, frame: Optional[int] = None):
    """Import *filepath* (OBJ) into the current scene and return the object."""
    import bpy

    name = os.path.splitext(os.path.basename(filepath))[0]
    if frame is not None:
        name = f"{name}_f{frame:06d}"

    bpy.ops.wm.obj_import(filepath=filepath)
    obj = context.selected_objects[-1] if context.selected_objects else None
    if obj:
        obj.name = name
    return obj


def load_ply_as_mesh(context, filepath: str, frame: Optional[int] = None):
    """Import *filepath* (PLY) into the current scene and return the object."""
    import bpy

    name = os.path.splitext(os.path.basename(filepath))[0]
    if frame is not None:
        name = f"{name}_f{frame:06d}"

    bpy.ops.wm.ply_import(filepath=filepath)
    obj = context.selected_objects[-1] if context.selected_objects else None
    if obj:
        obj.name = name
    return obj


# ---------------------------------------------------------------------------
# VTK legacy ASCII / binary loader (POLYDATA and UNSTRUCTURED_GRID)
# ---------------------------------------------------------------------------

class VTKFile:
    """Minimal parser for VTK legacy ASCII format files (POLYDATA / UNSTRUCTURED_GRID).

    Also recognises STRUCTURED_POINTS headers and exposes *dimensions*,
    *origin*, and *spacing* attributes for volume data files.
    """

    def __init__(self, filepath: str):
        self.filepath = filepath
        self.points: list = []   # list of (x, y, z)
        self.cells: list = []    # list of vertex-index tuples
        self.cell_types: list = []
        self.point_data: dict = {}  # name -> flat list of floats
        # Structured-points metadata (filled for STRUCTURED_POINTS datasets)
        self.dimensions: Optional[tuple] = None   # (Nx, Ny, Nz)
        self.origin: Optional[tuple] = None       # (ox, oy, oz)
        self.spacing: Optional[tuple] = None      # (sx, sy, sz)
        self._parse()

    # ------------------------------------------------------------------
    def _parse(self):
        with open(self.filepath, "r", encoding="latin-1") as fh:
            lines = fh.read().splitlines()

        # VTK legacy header: 4 fixed lines (version, title, format, dataset)
        i = 4  # skip the 4 fixed header lines

        def _next_line():
            nonlocal i
            while i < len(lines):
                ln = lines[i].strip()
                i += 1
                if ln:
                    return ln
            return None

        while True:
            ln = _next_line()
            if ln is None:
                break
            parts = ln.split()
            if not parts:
                continue
            keyword = parts[0].upper()

            if keyword == "DIMENSIONS" and len(parts) >= 4:
                self.dimensions = (int(parts[1]), int(parts[2]), int(parts[3]))

            elif keyword == "ORIGIN" and len(parts) >= 4:
                self.origin = (float(parts[1]), float(parts[2]), float(parts[3]))

            elif keyword == "SPACING" and len(parts) >= 4:
                self.spacing = (float(parts[1]), float(parts[2]), float(parts[3]))

            elif keyword == "POINTS":
                n_pts = int(parts[1])
                coords = []
                while len(coords) < n_pts * 3:
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    coords.extend(float(v) for v in ln2.split())
                self.points = [
                    (coords[j], coords[j + 1], coords[j + 2])
                    for j in range(0, len(coords), 3)
                ]

            elif keyword in ("CELLS", "POLYGONS", "LINES"):
                n_cells = int(parts[1])
                for _ in range(n_cells):
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    vals = list(map(int, ln2.split()))
                    self.cells.append(tuple(vals[1:]))  # drop leading count

            elif keyword == "CELL_TYPES":
                n_ct = int(parts[1])
                ct_vals = []
                while len(ct_vals) < n_ct:
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    ct_vals.extend(int(v) for v in ln2.split())
                self.cell_types = ct_vals

            elif keyword == "POINT_DATA":
                n_pts = int(parts[1])
                while True:
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    p2 = ln2.split()
                    attr_kw = p2[0].upper()
                    if attr_kw == "SCALARS" and len(p2) >= 2:
                        attr_name = p2[1]
                        _next_line()  # LOOKUP_TABLE line
                        values = []
                        while len(values) < n_pts:
                            ln3 = _next_line()
                            if ln3 is None:
                                break
                            values.extend(float(v) for v in ln3.split())
                        self.point_data[attr_name] = values
                    elif attr_kw == "VECTORS" and len(p2) >= 2:
                        attr_name = p2[1]
                        values = []
                        while len(values) < n_pts * 3:
                            ln3 = _next_line()
                            if ln3 is None:
                                break
                            values.extend(float(v) for v in ln3.split())
                        self.point_data[attr_name] = values
                    else:
                        # Unknown / end of POINT_DATA section – step back
                        i -= 1
                        break


def load_vtk_as_mesh(context, filepath: str, frame: Optional[int] = None):
    """Parse a VTK POLYDATA file and create a Blender mesh object.

    Returns the created *bpy.types.Object* or *None* on failure.
    """
    import bpy
    import bmesh

    try:
        vtk = VTKFile(filepath)
    except Exception as exc:
        log.error("Failed to parse VTK file %s: %s", filepath, exc)
        return None

    if not vtk.points:
        log.warning("VTK file %s has no POINTS data.", filepath)
        return None

    name = os.path.splitext(os.path.basename(filepath))[0]
    if frame is not None:
        name = f"{name}_f{frame:06d}"

    mesh = bpy.data.meshes.new(name)
    obj = bpy.data.objects.new(name, mesh)
    context.collection.objects.link(obj)

    bm = bmesh.new()
    verts = [bm.verts.new(pt) for pt in vtk.points]
    bm.verts.ensure_lookup_table()

    for cell in vtk.cells:
        if len(cell) >= 3:
            try:
                bm.faces.new([verts[ci] for ci in cell])
            except Exception:
                pass
        elif len(cell) == 2:
            try:
                bm.edges.new([verts[cell[0]], verts[cell[1]]])
            except Exception:
                pass

    bm.to_mesh(mesh)
    bm.free()
    mesh.update()

    return obj


# ---------------------------------------------------------------------------
# VDB volume sequence importer
# ---------------------------------------------------------------------------

def load_vdb_sequence(context, vdb_dir: str, start_frame: int = 1) -> Optional[object]:
    """Import a directory of ``.vdb`` files as an animated Blender Volume object.

    Blender's native OpenVDB support is used (``bpy.ops.object.volume_import``).
    Returns the created Volume object or None if no files are found.
    """
    import bpy
    import glob as _glob

    vdb_files = sorted(_glob.glob(os.path.join(vdb_dir, "*.vdb")))
    if not vdb_files:
        log.warning("No .vdb files found in %s", vdb_dir)
        return None

    first = vdb_files[0]
    filename = os.path.basename(first)

    bpy.ops.object.volume_import(
        filepath=first,
        files=[{"name": filename}],
        directory=vdb_dir,
    )

    vol_obj = context.selected_objects[-1] if context.selected_objects else None
    if vol_obj is None:
        return None

    # Set up sequence playback
    vol = vol_obj.data
    try:
        vol.sequence_mode = "CLAMP"
        vol.frame_start = start_frame
        vol.frame_duration = len(vdb_files)
        vol.frame_offset = 0
    except AttributeError:
        pass  # Older Blender builds may not expose all sequence attributes

    return vol_obj


# ---------------------------------------------------------------------------
# Frame-sequence helpers (surface meshes)
# ---------------------------------------------------------------------------

def collect_sequence_files(directory: str, extension: str) -> list:
    """Return sorted list of files with *extension* in *directory*."""
    if not os.path.isdir(directory):
        return []
    files = [
        os.path.join(directory, f)
        for f in sorted(os.listdir(directory))
        if f.lower().endswith(extension.lower())
    ]
    return files


def load_frame_sequence(context, directory: str, file_format: str, start_frame: int = 1):
    """Load all files of *file_format* from *directory* as individual mesh objects.

    Each mesh is hidden on all frames except its own, creating a simple
    frame-by-frame animation.

    Returns a list of created objects.
    """
    import bpy

    ext_map = {
        "OBJ": ".obj",
        "PLY": ".ply",
        "VTK": ".vtk",
    }
    ext = ext_map.get(file_format.upper(), ".vtk")
    files = collect_sequence_files(directory, ext)
    objects = []

    for idx, fp in enumerate(files):
        frame_num = start_frame + idx
        if file_format.upper() == "OBJ":
            obj = load_obj_as_mesh(context, fp, frame=frame_num)
        elif file_format.upper() == "PLY":
            obj = load_ply_as_mesh(context, fp, frame=frame_num)
        else:
            obj = load_vtk_as_mesh(context, fp, frame=frame_num)

        if obj is None:
            continue

        # Hide on all frames, show only on its own frame
        obj.hide_viewport = True
        obj.hide_render = True
        obj.keyframe_insert(data_path="hide_viewport", frame=0)
        obj.keyframe_insert(data_path="hide_render", frame=0)

        obj.hide_viewport = False
        obj.hide_render = False
        obj.keyframe_insert(data_path="hide_viewport", frame=frame_num)
        obj.keyframe_insert(data_path="hide_render", frame=frame_num)

        if idx + 1 < len(files):
            obj.hide_viewport = True
            obj.hide_render = True
            obj.keyframe_insert(data_path="hide_viewport", frame=frame_num + 1)
            obj.keyframe_insert(data_path="hide_render", frame=frame_num + 1)

        objects.append(obj)

    return objects

