"""Utility helpers for the FluidX_Blender addon.

Covers:
  - FluidX3D C++ setup-file generation
  - Loading OBJ / PLY surface meshes produced by FluidX3D
  - Loading legacy ASCII/binary VTK files (POLYDATA and UNSTRUCTURED_GRID)
    as Blender mesh objects or OpenVDB-backed volume objects
"""

import os
import logging
from typing import Optional

log = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# C++ setup-file generation
# ---------------------------------------------------------------------------

_SETUP_TEMPLATE = """\
// FluidX3D simulation setup – generated by FluidX_Blender
// Place this file as  <FluidX3D>/src/setup.cpp  and recompile.

#include "src/lbm.hpp"
#include "src/units.hpp"

void main_setup() {{
    // ---- Domain ----
    const uint Nx = {Nx}u;
    const uint Ny = {Ny}u;
    const uint Nz = {Nz}u;

    // ---- Physics ----
    // kinematic viscosity (lattice units); Re = u_max * L / nu
    const float nu = {nu}f;
    // fluid density (lattice units)
    const float rho = {rho}f;

    // ---- Boundary conditions ----
    // Each face: P=periodic  W=no-slip wall  F=free-slip  V=velocity
    const uchar  boundary_x_neg = {bc_x_neg};
    const uchar  boundary_x_pos = {bc_x_pos};
    const uchar  boundary_y_neg = {bc_y_neg};
    const uchar  boundary_y_pos = {bc_y_pos};
    const uchar  boundary_z_neg = {bc_z_neg};
    const uchar  boundary_z_pos = {bc_z_pos};

    LBM lbm(Nx, Ny, Nz, nu);

    // ---- Initial conditions ----
    // Set the initial density and velocity fields here.
    const uint n = lbm.get_N();
    for (uint i = 0u; i < n; i++) {{
        lbm.rho[i] = rho;
        lbm.u.x[i] = 0.0f;
        lbm.u.y[i] = 0.0f;
        lbm.u.z[i] = 0.0f;
        lbm.flags[i] = TYPE_F;  // fluid
    }}

    // ---- Boundary flags ----
    lbm.flags.write_to_device();
    lbm.rho.write_to_device();
    lbm.u.write_to_device();

    // ---- Output settings ----
    lbm.graphics.set_camera_free(
        float3(0.5f * Nx, -2.0f * Ny, 0.5f * Nz),
        float3(0.5f * Nx, 0.5f * Ny, 0.5f * Nz)
    );

    // ---- Run ----
    while (lbm.get_t() <= {time_steps}u) {{
        if (lbm.get_t() % {output_every}u == 0u) {{
#ifdef EXPORT_VTK
            lbm.vtk_export_lbm(lbm.get_t());
#endif
#ifdef EXPORT_MESH
            lbm.vtk_export_surface(lbm.get_t());
#endif
        }}
        lbm.run(1u, {time_steps}u);
    }}
}}
"""

# Map human-readable boundary names to FluidX3D flag characters
_BC_FLAG = {
    "PERIODIC": "TYPE_P",
    "WALL": "TYPE_W",
    "FREE_SLIP": "TYPE_S",
    "VELOCITY": "TYPE_V",
}


def generate_setup_code(props) -> str:
    """Return a FluidX3D setup.cpp string built from *props*."""

    def bc(name: str) -> str:
        return _BC_FLAG.get(name, "TYPE_W")

    return _SETUP_TEMPLATE.format(
        Nx=props.domain_res_x,
        Ny=props.domain_res_y,
        Nz=props.domain_res_z,
        nu=props.viscosity,
        rho=props.density,
        bc_x_neg=bc(props.bc_x_neg),
        bc_x_pos=bc(props.bc_x_pos),
        bc_y_neg=bc(props.bc_y_neg),
        bc_y_pos=bc(props.bc_y_pos),
        bc_z_neg=bc(props.bc_z_neg),
        bc_z_pos=bc(props.bc_z_pos),
        time_steps=props.time_steps,
        output_every=props.output_every,
    )


def write_setup_file(props, output_dir: str) -> str:
    """Write the generated setup.cpp to *output_dir* and return its path."""
    os.makedirs(output_dir, exist_ok=True)
    path = os.path.join(output_dir, "setup.cpp")
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(generate_setup_code(props))
    return path


# ---------------------------------------------------------------------------
# OBJ / PLY surface-mesh loader
# ---------------------------------------------------------------------------


def load_obj_as_mesh(context, filepath: str, frame: Optional[int] = None):
    """Import *filepath* (OBJ) into the current scene and return the object."""
    import bpy

    name = os.path.splitext(os.path.basename(filepath))[0]
    if frame is not None:
        name = f"{name}_f{frame:06d}"

    bpy.ops.wm.obj_import(filepath=filepath)
    obj = context.selected_objects[-1] if context.selected_objects else None
    if obj:
        obj.name = name
    return obj


def load_ply_as_mesh(context, filepath: str, frame: Optional[int] = None):
    """Import *filepath* (PLY) into the current scene and return the object."""
    import bpy

    name = os.path.splitext(os.path.basename(filepath))[0]
    if frame is not None:
        name = f"{name}_f{frame:06d}"

    bpy.ops.wm.ply_import(filepath=filepath)
    obj = context.selected_objects[-1] if context.selected_objects else None
    if obj:
        obj.name = name
    return obj


# ---------------------------------------------------------------------------
# VTK legacy ASCII / binary loader (POLYDATA and UNSTRUCTURED_GRID)
# ---------------------------------------------------------------------------

class VTKFile:
    """Minimal parser for VTK legacy ASCII format files (POLYDATA / UNSTRUCTURED_GRID)."""

    def __init__(self, filepath: str):
        self.filepath = filepath
        self.points: list = []   # list of (x, y, z)
        self.cells: list = []    # list of vertex-index tuples
        self.cell_types: list = []
        self.point_data: dict = {}  # name -> flat list of floats
        self._parse()

    # ------------------------------------------------------------------
    def _parse(self):
        with open(self.filepath, "r", encoding="latin-1") as fh:
            lines = fh.read().splitlines()

        # The VTK legacy format has exactly 4 fixed header lines:
        #   Line 0: "# vtk DataFile Version X.X"
        #   Line 1: title / description (any string)
        #   Line 2: "ASCII" or "BINARY"
        #   Line 3: "DATASET <type>"
        # Data sections start at line 4.  We must NOT treat the leading
        # "#" on line 0 as a comment because it is part of the format.
        i = 4  # skip the 4 fixed header lines

        def _next_line():
            nonlocal i
            while i < len(lines):
                ln = lines[i].strip()
                i += 1
                if ln:
                    return ln
            return None

        while True:
            ln = _next_line()
            if ln is None:
                break
            parts = ln.split()
            if not parts:
                continue
            keyword = parts[0].upper()

            if keyword == "POINTS":
                n_pts = int(parts[1])
                coords = []
                while len(coords) < n_pts * 3:
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    coords.extend(float(v) for v in ln2.split())
                self.points = [
                    (coords[j], coords[j + 1], coords[j + 2])
                    for j in range(0, len(coords), 3)
                ]

            elif keyword in ("CELLS", "POLYGONS", "LINES"):
                n_cells = int(parts[1])
                for _ in range(n_cells):
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    vals = list(map(int, ln2.split()))
                    self.cells.append(tuple(vals[1:]))  # drop leading count

            elif keyword == "CELL_TYPES":
                n_ct = int(parts[1])
                ct_vals = []
                while len(ct_vals) < n_ct:
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    ct_vals.extend(int(v) for v in ln2.split())
                self.cell_types = ct_vals

            elif keyword == "POINT_DATA":
                n_pts = int(parts[1])
                while True:
                    ln2 = _next_line()
                    if ln2 is None:
                        break
                    p2 = ln2.split()
                    attr_kw = p2[0].upper()
                    if attr_kw == "SCALARS" and len(p2) >= 2:
                        attr_name = p2[1]
                        _next_line()  # LOOKUP_TABLE line
                        values = []
                        while len(values) < n_pts:
                            ln3 = _next_line()
                            if ln3 is None:
                                break
                            values.extend(float(v) for v in ln3.split())
                        self.point_data[attr_name] = values
                    elif attr_kw == "VECTORS" and len(p2) >= 2:
                        attr_name = p2[1]
                        values = []
                        while len(values) < n_pts * 3:
                            ln3 = _next_line()
                            if ln3 is None:
                                break
                            values.extend(float(v) for v in ln3.split())
                        self.point_data[attr_name] = values
                    else:
                        # Unknown / end of POINT_DATA section – step back
                        i -= 1
                        break


def load_vtk_as_mesh(context, filepath: str, frame: Optional[int] = None):
    """Parse a VTK POLYDATA file and create a Blender mesh object.

    Returns the created *bpy.types.Object* or *None* on failure.
    """
    import bpy
    import bmesh as bm_module

    try:
        vtk = VTKFile(filepath)
    except Exception as exc:
        log.error("Failed to parse VTK file %s: %s", filepath, exc)
        return None

    if not vtk.points:
        log.warning("VTK file %s has no POINTS data.", filepath)
        return None

    name = os.path.splitext(os.path.basename(filepath))[0]
    if frame is not None:
        name = f"{name}_f{frame:06d}"

    mesh = bpy.data.meshes.new(name)
    obj = bpy.data.objects.new(name, mesh)
    context.collection.objects.link(obj)

    bm = bm_module.new()
    verts = [bm.verts.new(pt) for pt in vtk.points]
    bm.verts.ensure_lookup_table()

    for cell in vtk.cells:
        if len(cell) >= 3:
            try:
                bm.faces.new([verts[ci] for ci in cell])
            except Exception:
                pass
        elif len(cell) == 2:
            try:
                bm.edges.new([verts[cell[0]], verts[cell[1]]])
            except Exception:
                pass

    bm.to_mesh(mesh)
    bm.free()
    mesh.update()

    return obj


# ---------------------------------------------------------------------------
# Frame-sequence helpers
# ---------------------------------------------------------------------------

def collect_sequence_files(directory: str, extension: str) -> list:
    """Return sorted list of files with *extension* in *directory*."""
    if not os.path.isdir(directory):
        return []
    files = [
        os.path.join(directory, f)
        for f in sorted(os.listdir(directory))
        if f.lower().endswith(extension.lower())
    ]
    return files


def load_frame_sequence(context, directory: str, file_format: str, start_frame: int = 1):
    """Load all files of *file_format* from *directory* as individual mesh objects.

    Each mesh is hidden on all frames except its own, creating a simple
    frame-by-frame animation.

    Returns a list of created objects.
    """
    import bpy

    ext_map = {
        "OBJ": ".obj",
        "PLY": ".ply",
        "VTK": ".vtk",
    }
    ext = ext_map.get(file_format.upper(), ".vtk")
    files = collect_sequence_files(directory, ext)
    objects = []

    for idx, fp in enumerate(files):
        frame_num = start_frame + idx
        if file_format.upper() == "OBJ":
            obj = load_obj_as_mesh(context, fp, frame=frame_num)
        elif file_format.upper() == "PLY":
            obj = load_ply_as_mesh(context, fp, frame=frame_num)
        else:
            obj = load_vtk_as_mesh(context, fp, frame=frame_num)

        if obj is None:
            continue

        # Hide on all frames, show only on its own frame
        obj.hide_viewport = True
        obj.hide_render = True
        obj.keyframe_insert(data_path="hide_viewport", frame=0)
        obj.keyframe_insert(data_path="hide_render", frame=0)

        obj.hide_viewport = False
        obj.hide_render = False
        obj.keyframe_insert(data_path="hide_viewport", frame=frame_num)
        obj.keyframe_insert(data_path="hide_render", frame=frame_num)

        if frame_num + 1 <= start_frame + len(files):
            obj.hide_viewport = True
            obj.hide_render = True
            obj.keyframe_insert(data_path="hide_viewport", frame=frame_num + 1)
            obj.keyframe_insert(data_path="hide_render", frame=frame_num + 1)

        objects.append(obj)

    return objects
